MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.09.20

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,37 +8,59 @@ osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_PY=27
-    - CONDA_PY=35
-    - CONDA_PY=36
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.5
+    - CONFIG=osx_python3.6
+    - CONFIG=osx_python3.7
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
     - secure: "Wq/C+LiIcKjr3sxNqtxBtCL46qx5fGYHMxcoMVlDD18sonp1yGMlHOHYYiQ77JL8iHGufRFZp9qc8lnk8oxDA5/FJSFUNZ1c7NaeiYDEQkkKGGPNDsp9QLqiwJ7rqJYKQNgqwuXauMgwnpAGu/GR2lNypF3I48JeS6XNN6X6YAJJuuBBCjhYuf7rM+y/oM6I6mOuzhtwJxIhbKSooLuF2GTwNQGwdyRb6osWfe3+bSD6Voew5okDoOwR+O/flnAkq2r3jpmyAvqRX/lq2vJ8YHEPNnZqGE5t28KMBVqH5iKqee0ZLKFmjnisqIYGev1miagUHA6+9pXCYsaZCXuhCcqgpeFyQkGZDwpCf7MOBETbLh5i8yt7Ao4qbkoYD10ThN/B2r6hKPI3x5bnuiIXihEKWCV3ZRMUosguIo6bSAn2hngRpMKnmaCZAG4Hpro8eVixo4HLFlAs7Zzg9fcQq5GlSfSLZwmOAhEYmYBghpjU7RMLOnSOJet0yUAG5kizO/2Y5pPM8UaVXdKN8ugSxkP506e+7P2cWPJsV1vpXYi4HO5yhfeuQVkwwIGm2dqqTz4mEv29U4P/Fvxc89JW1SmOVst7V6W4lbLR//0ZgyIgXdnBiQQ96FFxaa6ZCjqpsWCzL5UOrWTsMzuv48QTLqY0inbyfwPX6CLgEvto44Q="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force --ignore-dependencies $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --remove channels defaults
-      conda config --add channels defaults
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=main
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
